version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PORTS}
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  app:
    env_file: .env
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8501:8501

volumes:
  pg_data:
